### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by ArtHoffmann** [mcrovero/flutter_sqflite_manager#1]
Hello sir,
I have the problem right now, 
that I can't see the contents of the local db.
However, I get all my databases displayed

The following error occurs:

Failed assertion: line 279 pos 15: '!rows.any((DataRow row) => row.cells.length != columns.length)': is not true.

![image](https://user-images.githubusercontent.com/24555132/64099131-d4ae5b00-cd68-11e9-9335-74e7757c248d.png)

![image](https://user-images.githubusercontent.com/24555132/64099153-de37c300-cd68-11e9-9687-651c1740d5d2.png)

I guess it's the column PRIMARY. Where i get the assert Exception

**Comment by synw** [comment]
Same here. I tried to just comment the assertion and it worked

**Comment by ArtHoffmann** [comment]
still exists. if i comment out, i get the RangeError(index): Invalid value: Not in range 0..6, inclusive: 7

**Comment by ArtHoffmann** [comment]
i have fixed the bug, i forked it

**Comment by synw** [comment]
Can we make a release with this fix?
